	// ----------------------------------- Log matricies ------------------------------------------------
	float testMtx[16];
	memcopy(testMtx, torusUniforms.torusMtx,sizeof(testMtx));
	setcammatrix();
	prepMatrix(testMtx);
	logfile *l = newlogfile("testPrimitives.txt");
	l->log("Model Matrix:");
	l->log("------------------");
	logMatrix(testMtx, l);
	l->log("");
	l->log("Inverted Camera Matrix:");
	l->log("-----------------------");
	logMatrix(invcammat, l);
	l->log("");
	l->log("ModelView Matrix (modelMatrix * invcammat)");
	l->log("----------------");
	logMatrix(modelViewMatrix, l);
	l->log("");
	l->log("Projection Matrix:");
	l->log("------------------");
	logMatrix(projectionMatrix, l);
	l->log("");
	l->log("ModelViewProjection Matrix (modelMatrix * invcammat * ProjectionMat)");
	l->log("--------------------------");
	logMatrix(modelViewProjectionMatrix, l);
	l->log("");
	float3 src = {-100.0f,-100.0f,-100.0f};
	float3 dst;
	transformPointByMatrix(&dst, modelViewProjectionMatrix, &src);
	l->log("(%6.2f,  %6.2f,  %6.2f) -> (%6.2f, %6.2f, %6.2f)",src.x,src.y,src.z,dst.x,dst.y,dst.z);
	src.x = src.y = src.z = 100.0f;
	transformPointByMatrix(&dst, modelViewProjectionMatrix, &src);
	l->log("(%6.2f,  %6.2f,  %6.2f) -> (%6.2f, %6.2f, %6.2f)",src.x,src.y,src.z,dst.x,dst.y,dst.z);
	delete l;
